import {
  parseDefinition,
  initialPackageSource,
} from "@/lib/platform-authoring/package-source";
import type { RunDetail, WorkflowPackage } from "@/lib/types/workflow-platform";
export const packageFixture: WorkflowPackage = {
  id: "example",
  key: "example",
  name: "Example",
  description: "",
  source: initialPackageSource,
  definition: parseDefinition(initialPackageSource),
  plans: {
    main: {
      workflowKey: "main",
      nodeOrder: ["answer"],
      dependencies: { answer: [] },
      edges: [],
    },
  },
  packageHash: "sha256:abc",
  createdAt: "2026-09-08T00:00:00Z",
  updatedAt: "2026-09-08T00:00:00Z",
};
export const runFixture: RunDetail = {
  id: "run-1",
  packageKey: "example",
  workflowKey: "main",
  packageHash: "sha256:abc",
  status: "running",
  createdAt: "2026-09-08T00:00:00Z",
  origin: { kind: "manual" },
  output: null,
  spec: {
    runId: "run-1",
    packageKey: "example",
    workflowKey: "main",
    packageHash: "sha256:abc",
    definition: packageFixture.definition,
    plan: packageFixture.plans.main,
    parameters: {},
    modelBindings: {},
    pluginReleases: [],
    resourceBindings: {},
    toolAliases: {},
    coreArtifact: "sha256:core",
    deadline: "2026-09-08T01:00:00Z",
    origin: { kind: "manual" },
  },
  evidence: [
    {
      id: "node-1",
      runId: "run-1",
      parentId: null,
      nodeId: "answer",
      kind: "node",
      status: "running",
      attempt: 1,
      input: {},
      output: null,
      metadata: {},
    },
    {
      id: "agent-1",
      runId: "run-1",
      parentId: "node-1",
      nodeId: "answer",
      kind: "agent",
      status: "running",
      attempt: 1,
      input: {},
      output: null,
      metadata: {},
    },
    {
      id: "tool-1",
      runId: "run-1",
      parentId: "agent-1",
      nodeId: "answer",
      kind: "tool",
      status: "unknown",
      operationId: "operation-stable",
      attempt: 1,
      input: {},
      output: null,
      metadata: {},
    },
  ],
};
